### ISSUE TITLE
"I like this tool" button

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#22]

**Comment by petelandvt** [comment]
Currently on staging (test) site. See demo of buttons below content area on dev tool content type (e.g. Fido @ /library/fido). Only accessible by  authenticated users.''

Note that this is not packaged as a feature; simply enable the Rate module and  re-create the widget though the UI after deploying to Live.  See comment on "I built this tool" card for more details.

**Comment by rjcorwin** [comment]
Looks like anonymous users are not seeing the icon and metadata around `likes`. Placed this one back in `slated`.

<img width="1280" alt="screen shot 2015-10-16 at 9 35 58 am" src="https://cloud.githubusercontent.com/assets/156575/10542927/8b2c9cf8-73e9-11e5-8b25-f390d77ae476.png">

**Comment by rjcorwin** [comment]
Reviewed with authenticated and anonymous users. Authenticated can see data and submit. Anonymous users can see data but cannot submit. Marking as done.
