### ISSUE TITLE
"I built (or modified) this tool" button

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#23]

**Comment by petelandvt** [comment]
Currently on staging (test) site. See demo of buttons below content area on dev tool content type (e.g. Fido @ /library/fido). Only accessible by  authenticated users.

Note that this is not packaged as a feature; simply enable the Rate module and  re-create the widget though the UI after deploying to Live.

**Comment by petelandvt** [comment]
GOALS: Should be similar to Liking/Hearting/etc in social media. Should show #. Put this and the "I like this tool" button next to each other (so, we need a solution that supports multiple widgets).

RESEARCHED MODULES:
1) LikeBtn
• has free version but costs up to $39/year for full functionality
• no capacity for multiple widgets
• seems buggy (couldn’t get it to take more than one like… IP address dependent?) and very little issue documentation
2) Plus1 
• already installed for ‘hacker points’ on hack content type
• seems to work well (would just swap in icon for text and theme appropriately)
• good views integration
• no capacity for multiple widgets 
3) Rate
• Works!  And supports multiple widgets!  
• Created the two buttons as "thumbs up" widgets @ /admin/structure/rate)

TO DO: 
• Default shows "thumbs up" icons; we can theme to show heart/tool icons 
• Defaults shows # as "2 users have voted"; we can override counter message by customizing module (or via CSS)
• Try to put buttons within a fieldset

**Comment by rjcorwin** [comment]
Reviewed with authenticated and anonymous users. Authenticated can see data and submit. Anonymous users can see data but cannot submit. Marking as done.
