### ISSUE TITLE
"Add impact assessment report" button on tools

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#24]

**Comment by petelandvt** [comment]
Currently on Dev.  Will update when pushed to Test.

**Comment by petelandvt** [comment]
See example: http://dev.farmhack.gotpantheon.com/library/fido

Look for:
• the new "Impact" fieldset 
• the fieldset includes a link to create a new report for that tool, plus links to any existing reports already created for that tool
• titles for the reports are generated automatically (based on user authoring the report and the tool they're reporting on)
• help text at top of the report form specifies which tool is being reported on
• Filtered HTML input format now includes CKEditor + IMCE (rich text editor toolbar + option to upload files)
• URL alias generated for report follows this pattern: /library/[toolname]/report/[report node id]

**Comment by petelandvt** [comment]
@rjsteinert  - Note that I've turned off the "Limit allowed HTML tags" option in our Filtered HTML text format because it was stripping out the inline sizes applied to images.  If we want to limit HTML tags while still allowing inline image sizes, we'll need to create a new text format, as this article suggests:

http://docs.cksource.com/CKEditor_for_Drupal/Enterprise/Drupal_7/Inline_Styles

**Comment by petelandvt** [comment]
I bundled the UI improvements (CKEditor WYSIWG on Filtered HTML text format and administration views) within an Impact Assessment Reports feature.

Notes for deployment:
• Disable External Links module (creates js conflict with IMCE buttons, tool fieldset expansion, etc.)
• Enable these modules: Impact Assessment Reports (Feature), Views Contextual Filter Query, Entity Reference Prepopulate, Administration Views, Views Bulk Operations, CKEditor, IMCE
• Configure the Impact Assessment Report Header views block so it appears just above main content in all themes, only on this URL: node/add/impact-assessment-report*
• Add URL alias pattern for impact assessment report nodes: [node:field-tool-impact:url:path]/report/[node:nid]
• Configure Filtered Text format to allow authenticated user access
• Configure CKEditor profiles to allow Filtered Text to use Full
• Configure IMCE to allow authenticated user access to User-1 profile
