### ISSUE TITLE
Create better admin interfaces for managing Content/People

### ISSUE THREAD

**Issue by petelandvt** [FarmHack/FarmHack.org#35]
Admin Views module installed & configured.  The system Content & People admin tables have been replaced with custom views with more columns and additional search filters.  These can be further customized @ /admin/structure/views

**Comment by petelandvt** [comment]
This is currently up and working  (just go to the People and Content management tables).  I removed the unused Admin Menu module, which created a conflict on Live.

**Comment by rjcorwin** [comment]
Just tested with the `user1` account. Works great!
