### ISSUE TITLE
Add mapping of location-tagged content

### ISSUE THREAD

**Issue by petelandvt** [FarmHack/FarmHack.org#36]
After encountering numerous errors, I scrapped the idea of using OpenLayers3 for now, since we can easily get an OpenLayers2 map up and running.  Will retry using OpenLayers2 ASAP.

**Comment by petelandvt** [comment]
Events Map has been rebuilt /wOpenLayers2.

Preview on Dev: http://dev.farmhack.gotpantheon.com/calendar/map

Showed to Dorn on 10/30.  Folks should feel free to play around with the OpenLayers behaviors for the map (clustering, etc.).

**Comment by petelandvt** [comment]
@Dornawcox, @rjsteinert --- should I go ahead and deploy this to the Live site?  Still sitting on Dev.

**Comment by Dornawcox** [comment]
Let's take it live.  I have not played with the clusters etc. Much yet, but
that can be a refinement over time as we gather feedback.

Dorn Cox
603.781.6030

**Comment by petelandvt** [comment]
Ok, great, I will push this up with the Public Lab calendar feed.

**Comment by rjcorwin** [comment]
+1

**Comment by petelandvt** [comment]
Events map is now on Live: http://farmhack.org/calendar/map

Linked from List/Calendar displays.

**Comment by rjcorwin** [comment]
@petelandvt I threw that map into a block and highlighted it on the usual calendar/month page. What do you think? http://farmhack.org/calendar/month

**Comment by petelandvt** [comment]
Nice, @rjsteinert!

**Comment by Dornawcox** [comment]
I like it!

Dorn Cox
603.781.6030
