### ISSUE TITLE
Filtered HTML text format stripping out inline image dimensions

### ISSUE THREAD

**Issue by petelandvt** [FarmHack/FarmHack.org#37]

**Comment by petelandvt** [comment]
@mstenta - Given your experience with OpenLayers 3, do you happen to know how we can customize markers?

**Comment by mstenta** [comment]
@petelandvt - Sorry I'm a bit out of the loop here... what markers do you want to customize? Also not sure what this "Filtered HTML text format stripping out inline image dimensions" issue is - is it related to the Openlayers question?

**Comment by mstenta** [comment]
Oh, Dorn just emailed me...
