### ISSUE TITLE
Google analytics seems to be not tracking anymore

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#53]
I think the old theme had some Google Analytics code on the page template. Now either the new theme needs the same code or we need to use the Google Analytics module to place that code.

**Comment by rjcorwin** [comment]
@petelandvt Daniel is adding you to the Google Analytics account.

**Comment by petelandvt** [comment]
@rjsteinert - Not sure how the GA tracking code had been integrated into the site, but it no longer appears to be there.  I can simply add the tracking code manually to the html template or use the Google Analytics module to provide a UI for integration.  We generally do the latter. Let me know your preference.

**Comment by rjcorwin** [comment]
I had issues with Google Analytics module in the past theme but in the current theme I think it will work. Try that out first.

**Comment by petelandvt** [comment]
Ok will do.

**Comment by petelandvt** [comment]
Google Analytics module updated and enabled on Live.  Will check in a couple days to make sure it's tracking again.

**Comment by rjcorwin** [comment]
Woohoo we have data! I just confirmed.

**Comment by danibgrover** [comment]
Wahoooo analysis!!

On Sun, Dec 20, 2015 at 8:02 PM, R.J. Steinert notifications@github.com
wrote:

> Closed #53 https://github.com/FarmHack/FarmHack.org/issues/53.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FarmHack/FarmHack.org/issues/53#event-496989536.

## 

Daniel Grover
FarmHack http://farmhack.net/home/, Network Facilitator
Draft Animal Power Network http://draftanimalpower.com/
703.965.7636
