### ISSUE TITLE
Add NEFKE Tag Vocabulary to tools

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#55]

**Comment by petelandvt** [comment]
Awaiting response from @Dornawcox before proceeding.  

Setting this up as a free-tagging field seems like it might be redundant... we already have free tagging ("Tags") field on the new tool content type.  An alternative would be to include the NEFKE Taxonomy field with its controlled list of terms, but to make it collapsed by default (so the long list of checkboxes doesn't clutter up the form).

**Comment by petelandvt** [comment]
Added to Live, including help text.
