### ISSUE TITLE
Hide "Archive ID" field from Tool 2.0 form

### ISSUE THREAD

**Issue by petelandvt** [FarmHack/FarmHack.org#58]
I propose that we use the Field Permissions module to keep this field behind the scenes so it doesn't confuse users.

**Comment by Dornawcox** [comment]
I agree.

Dorn Cox
603.781.6030

**Comment by petelandvt** [comment]
Field Permissions module installed and enabled on Live.  Archive ID field no longer displaying except for Administrators.
