### ISSUE TITLE
Include Public Lab events in calendar

### ISSUE THREAD

**Issue by petelandvt** [FarmHack/FarmHack.org#59]
Create feed importer that reads an iCal feed provided by Public Lab

**Comment by petelandvt** [comment]
I've successfully imported Public Lab's test feed on Farm Hack Dev.  

To do:
• Deploy Date iCal module & library
• Add a new "Public Lab Events" option to the events filter

**Comment by petelandvt** [comment]
I'll deploy this along with the map stuff ASAP.

**Comment by rjcorwin** [comment]
+1

**Comment by petelandvt** [comment]
The feed importer is now active on Live.  You can find 9 events (authored by Public Lab)  imported thus far.  Also added a "Public Lab" filter to the Events list/calendar.
