### ISSUE TITLE
Migrate images from archived tool posts to the new tool posts

### ISSUE THREAD

**Issue by rjcorwin** [FarmHack/FarmHack.org#60]
We'll need to create a new field on the Tool content type called "Image Gallery" and then migrate the old images attached to archived posts to the new Tools.  Mike suggest that the `insert` module could be a nice addition to easily add an image from the gallery to the documentation field. https://www.drupal.org/project/insert

Having an annotation/description for an image in the gallery is a big plus.

**Comment by petelandvt** [comment]
I just updated Dev to use the Live database so I can play around with the migrated data.

**Comment by petelandvt** [comment]
@rjsteinert @Dornawcox
Hey guys, I've got a question.  We already migrated the "Representative Image" field to the new Tools.  Do we want to  (a) keep the "Representative Image" as is, but also add an "Image Gallery" field, or (b) consolidate all images within a single field?

If the answer is (a), I can proceed with migrating the Wiki images to the new field.  If (b), it'll be a bit more complicated, as I'll first need to get all of the representative images exported and then consolidated with the Wiki images before migration, but certainly possible.

Let me know your preference.  Thanks!

**Comment by rjcorwin** [comment]
Option A I think works best, keep the "Representative Image" as is, but
also add an "Image Gallery" field.  Thanks!
- RJ

Web Developer at RTI, Javascript Ninja, Farm Hacker, Unix Philosophy for
IoT Evangelist
rj@rjsteinert.com
http://rjsteinert.com
http://twitter.com/rjsteinert
http://github.com/rjsteinert

**Comment by Dornawcox** [comment]
I agree

Dorn Cox
603.781.6030

**Comment by petelandvt** [comment]
OK, thanks.   Migration complete on Live!  You'll find a new "Image Gallery" field within the Documentation section.   All Wiki images (including alt/title data) have been migrated to this field.   I also wrote instructions on how to add the images to the "Documentation Wiki" field using the Insert module.   All of this is tested and functional.

I'm also displaying thumbnails of the Image Gallery images below the Documentation Wiki (trying to use Lightbox display, but that doesn't appear to be working for me).  @rjsteinert, feel free to adjust how these are displayed and/or look into the Lightbox issue.
