### ISSUE TITLE
Change "Watch our movie" text on main page to "Watch our movie. Get started here."

### ISSUE THREAD

**Issue by KristenLoria** [FarmHack/FarmHack.org#64]

**Comment by rjcorwin** [comment]
Got it!

**Comment by KristenLoria** [comment]
the new menu looks stellar!

On Thu, Jan 28, 2016 at 7:31 PM, R.J. Steinert notifications@github.com
wrote:

> Closed #64 https://github.com/FarmHack/FarmHack.org/issues/64.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/FarmHack/FarmHack.org/issues/64#event-530613782.

## 

Farmer @ Sparrowbush Farm
Network Facilitator @ Farm Hack http://www.farmhack.org
